apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sb
spec:
  rules:
    - host: edpDefault
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sb
                port:
                  number: 80